name: core
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: ^1.0.0
  fixnum: ^0.10.11 
  intl: ^0.16.1
  api:
    path: ../api

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
